//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("login.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _0006 {
            get {
                object obj = ResourceManager.GetObject("0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00061 {
            get {
                object obj = ResourceManager.GetObject("00061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0007 {
            get {
                object obj = ResourceManager.GetObject("0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0009 {
            get {
                object obj = ResourceManager.GetObject("0009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0014 {
            get {
                object obj = ResourceManager.GetObject("0014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0016 {
            get {
                object obj = ResourceManager.GetObject("0016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0017 {
            get {
                object obj = ResourceManager.GetObject("0017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00171 {
            get {
                object obj = ResourceManager.GetObject("00171", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0018 {
            get {
                object obj = ResourceManager.GetObject("0018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00181 {
            get {
                object obj = ResourceManager.GetObject("00181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00182 {
            get {
                object obj = ResourceManager.GetObject("00182", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0019 {
            get {
                object obj = ResourceManager.GetObject("0019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0020 {
            get {
                object obj = ResourceManager.GetObject("0020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0025 {
            get {
                object obj = ResourceManager.GetObject("0025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0043 {
            get {
                object obj = ResourceManager.GetObject("0043", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0044 {
            get {
                object obj = ResourceManager.GetObject("0044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00441 {
            get {
                object obj = ResourceManager.GetObject("00441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20170727_105325 {
            get {
                object obj = ResourceManager.GetObject("20170727_105325", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20170727_105341 {
            get {
                object obj = ResourceManager.GetObject("20170727_105341", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20170727_1053411 {
            get {
                object obj = ResourceManager.GetObject("20170727_1053411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20170727_105444 {
            get {
                object obj = ResourceManager.GetObject("20170727_105444", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20170727_105636 {
            get {
                object obj = ResourceManager.GetObject("20170727_105636", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20170727_105709 {
            get {
                object obj = ResourceManager.GetObject("20170727_105709", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20170727_131121 {
            get {
                object obj = ResourceManager.GetObject("20170727_131121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20170727_131206 {
            get {
                object obj = ResourceManager.GetObject("20170727_131206", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BACKGROUNDS_MAIN_1 {
            get {
                object obj = ResourceManager.GetObject("BACKGROUNDS_MAIN_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BACKGROUNDS_MAIN_11 {
            get {
                object obj = ResourceManager.GetObject("BACKGROUNDS_MAIN_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Capture {
            get {
                object obj = ResourceManager.GetObject("Capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Capture1 {
            get {
                object obj = ResourceManager.GetObject("Capture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Capture11 {
            get {
                object obj = ResourceManager.GetObject("Capture11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Capture111 {
            get {
                object obj = ResourceManager.GetObject("Capture111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Capture12 {
            get {
                object obj = ResourceManager.GetObject("Capture12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Capture3 {
            get {
                object obj = ResourceManager.GetObject("Capture3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Capture33 {
            get {
                object obj = ResourceManager.GetObject("Capture33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Capture5 {
            get {
                object obj = ResourceManager.GetObject("Capture5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CaptureBeam2 {
            get {
                object obj = ResourceManager.GetObject("CaptureBeam2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chocket {
            get {
                object obj = ResourceManager.GetObject("Chocket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chocket2 {
            get {
                object obj = ResourceManager.GetObject("chocket2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chocket21 {
            get {
                object obj = ResourceManager.GetObject("chocket21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chocket22 {
            get {
                object obj = ResourceManager.GetObject("chocket22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chocket23 {
            get {
                object obj = ResourceManager.GetObject("chocket23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chocket24 {
            get {
                object obj = ResourceManager.GetObject("chocket24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chockett {
            get {
                object obj = ResourceManager.GetObject("Chockett", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_IMG_1495437333397 {
            get {
                object obj = ResourceManager.GetObject("FB_IMG_1495437333397", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_IMG_1495437336822 {
            get {
                object obj = ResourceManager.GetObject("FB_IMG_1495437336822", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_IMG_1495633140949 {
            get {
                object obj = ResourceManager.GetObject("FB_IMG_1495633140949", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_IMG_1495633146964 {
            get {
                object obj = ResourceManager.GetObject("FB_IMG_1495633146964", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_IMG_1495633457563 {
            get {
                object obj = ResourceManager.GetObject("FB_IMG_1495633457563", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FB_IMG_1497678327194 {
            get {
                object obj = ResourceManager.GetObject("FB_IMG_1497678327194", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gutter1 {
            get {
                object obj = ResourceManager.GetObject("Gutter1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iii {
            get {
                object obj = ResourceManager.GetObject("iii", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_083 {
            get {
                object obj = ResourceManager.GetObject("images_083", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images_0831 {
            get {
                object obj = ResourceManager.GetObject("images_0831", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_1856 {
            get {
                object obj = ResourceManager.GetObject("IMG_1856", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_18561 {
            get {
                object obj = ResourceManager.GetObject("IMG_18561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_18562 {
            get {
                object obj = ResourceManager.GetObject("IMG_18562", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_1868 {
            get {
                object obj = ResourceManager.GetObject("IMG_1868", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_1872 {
            get {
                object obj = ResourceManager.GetObject("IMG_1872", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_18721 {
            get {
                object obj = ResourceManager.GetObject("IMG_18721", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_18722 {
            get {
                object obj = ResourceManager.GetObject("IMG_18722", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_1882 {
            get {
                object obj = ResourceManager.GetObject("IMG_1882", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_18821 {
            get {
                object obj = ResourceManager.GetObject("IMG_18821", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_18822 {
            get {
                object obj = ResourceManager.GetObject("IMG_18822", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170617_123130 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170617_123130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170617_123147 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170617_123147", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170617_1231471 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170617_1231471", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170617_123207 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170617_123207", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170617_123228 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170617_123228", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170617_123557 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170617_123557", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170619_122104 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170619_122104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170619_1221041 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170619_1221041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105259 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105259", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_1053281 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_1053281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105402 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105402", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105410 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105410", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105441 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_1054411 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_1054411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105515 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105515", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105537 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105537", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105540 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105540", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105617 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105617", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105626 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105626", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_1056261 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_1056261", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105645 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105645", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105652 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105652", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105744 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105744", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_1057441 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_1057441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_1057442 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_1057442", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_1057443 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_1057443", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_1057444 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_1057444", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170727_105754 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_105754", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_192434 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_192434", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_192541 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_192541", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_192555 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_192555", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_192603 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_192603", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_192609 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_192609", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_192623 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_192623", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_1926231 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_1926231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_192630 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_192630", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_192709 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_192709", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_192716 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_192716", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_211845 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_211845", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_212121 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_212121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_2121211 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_2121211", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170728_212128 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170728_212128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170731_071326 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170731_071326", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170731_071621 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170731_071621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20170731_072115 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170731_072115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_36286771010701 {
            get {
                object obj = ResourceManager.GetObject("IMG_36286771010701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pp2 {
            get {
                object obj = ResourceManager.GetObject("pp2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_220959391749667 {
            get {
                object obj = ResourceManager.GetObject("received_220959391749667", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_251435632001520 {
            get {
                object obj = ResourceManager.GetObject("received_251435632001520", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_316888845408692 {
            get {
                object obj = ResourceManager.GetObject("received_316888845408692", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_320017668429143 {
            get {
                object obj = ResourceManager.GetObject("received_320017668429143", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_332578487173061 {
            get {
                object obj = ResourceManager.GetObject("received_332578487173061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341571752940401 {
            get {
                object obj = ResourceManager.GetObject("received_341571752940401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341572156273694 {
            get {
                object obj = ResourceManager.GetObject("received_341572156273694", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341572192940357 {
            get {
                object obj = ResourceManager.GetObject("received_341572192940357", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341572242940352 {
            get {
                object obj = ResourceManager.GetObject("received_341572242940352", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341572489606994 {
            get {
                object obj = ResourceManager.GetObject("received_341572489606994", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341572526273657 {
            get {
                object obj = ResourceManager.GetObject("received_341572526273657", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341572696273640 {
            get {
                object obj = ResourceManager.GetObject("received_341572696273640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341572719606971 {
            get {
                object obj = ResourceManager.GetObject("received_341572719606971", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341572722940304 {
            get {
                object obj = ResourceManager.GetObject("received_341572722940304", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_341572749606968 {
            get {
                object obj = ResourceManager.GetObject("received_341572749606968", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_528947487437895 {
            get {
                object obj = ResourceManager.GetObject("received_528947487437895", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_528947510771226 {
            get {
                object obj = ResourceManager.GetObject("received_528947510771226", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_528947534104557 {
            get {
                object obj = ResourceManager.GetObject("received_528947534104557", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_528947560771221 {
            get {
                object obj = ResourceManager.GetObject("received_528947560771221", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap received_528947574104553 {
            get {
                object obj = ResourceManager.GetObject("received_528947574104553", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Roof1 {
            get {
                object obj = ResourceManager.GetObject("Roof1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Roof2 {
            get {
                object obj = ResourceManager.GetObject("Roof2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Room {
            get {
                object obj = ResourceManager.GetObject("Room", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_03_11_51_53 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-03-11-51-53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_03_11_51_531 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-03-11-51-531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_05_14_33_23 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-05-14-33-23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_05_14_47_31 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-05-14-47-31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_05_14_47_311 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-05-14-47-311", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_05_20_37_28 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-05-20-37-28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_05_20_40_14 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-05-20-40-14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_14_08_34_11 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-14-08-34-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_22_22_13_03 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-22-22-13-03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_22_22_25_04 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-22-22-25-04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_25_12_57_00 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-25-12-57-00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_25_12_57_33 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-25-12-57-33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_25_12_57_331 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-25-12-57-331", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_25_12_58_28 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-25-12-58-28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_25_12_58_281 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-25-12-58-281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_25_13_01_56 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-25-13-01-56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_25_13_02_22 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-25-13-02-22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_25_13_02_221 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-25-13-02-221", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_25_20_51_41 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-25-20-51-41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_17_16 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-17-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_21_26 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-21-26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_22_09 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-22-09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_26_56 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-26-56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_30_37 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-30-37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_32_51 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-32-51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_35_30 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-35-30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_38_26 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-38-26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_38_47 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-38-47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_40_02 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-40-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_2017_07_26_17_40_30 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2017-07-26-17-40-30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Seasons_06 {
            get {
                object obj = ResourceManager.GetObject("Seasons_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stair {
            get {
                object obj = ResourceManager.GetObject("stair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stair1 {
            get {
                object obj = ResourceManager.GetObject("stair1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stair2 {
            get {
                object obj = ResourceManager.GetObject("stair2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stair3 {
            get {
                object obj = ResourceManager.GetObject("stair3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled1 {
            get {
                object obj = ResourceManager.GetObject("Untitled1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wall9inches {
            get {
                object obj = ResourceManager.GetObject("Wall9inches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
